# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=server_001
ENV POSTGRES_USER=server_001
ENV POSTGRES_PASSWORD=server_001

# Expose the PostgreSQL port
EXPOSE 5432
