version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django

  postgresql:
    build:
      context: ./postgresql
    environment:
      POSTGRES_DB: server_001
      POSTGRES_USER: server_001
      POSTGRES_PASSWORD: server_001
    ports:
      - "5432:5432"

  django:
    build:
      context: ./django
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
